create table if not exists public.tienda_inventory_warning_log (
  id bigint generated by default as identity primary key,
  id_tienda bigint not null unique,
  last_inventory_date date not null,
  last_notified_at date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tienda_inventory_warning_log_tienda_idx
  on public.tienda_inventory_warning_log (id_tienda);

create extension if not exists pg_cron;
create extension if not exists pg_net;

select
  cron.unschedule(jobid)
from cron.job
where jobname = 'warning-notifications-daily';

select cron.schedule(
  'warning-notifications-daily',
  '30 12 * * *',
  $$
  select
    net.http_post(
      url := current_setting('app.settings.supabase_url') || '/functions/v1/warning-notifications',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key')
      ),
      body := '{}'::jsonb
    );
  $$
);
