create table if not exists public.action_plan_notification_log (
  id bigint generated by default as identity primary key,
  id_plan_accion bigint not null,
  notification_type text not null,
  reference_date date not null,
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint action_plan_notification_log_unique unique (id_plan_accion, notification_type, reference_date)
);

create index if not exists action_plan_notification_log_plan_idx
  on public.action_plan_notification_log (id_plan_accion);

create extension if not exists pg_cron;
create extension if not exists pg_net;

select
  cron.unschedule(jobid)
from cron.job
where jobname = 'action-plan-periodic-notifications-daily';

select cron.schedule(
  'action-plan-periodic-notifications-daily',
  '0 12 * * *',
  $$
  select
    net.http_post(
      url := current_setting('app.settings.supabase_url') || '/functions/v1/action-plan-periodic-notifications',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key')
      ),
      body := '{}'::jsonb
    );
  $$
);
